In [2]:
#downloading the dataset
import pandas as pd
true_news= pd.read_csv("/Users/kosireddyanirudhreddy/Downloads/News _dataset/True.csv")
fake_news= pd.read_csv("/Users/kosireddyanirudhreddy/Downloads/News _dataset/Fake.csv")

In [3]:
#inspecting the datasets to concatenate
true_news.head
true_news.columns
fake_news.columns
print(true_news.shape)
fake_news.shape

(21417, 4)


(23481, 4)

In [4]:
#concatenating the datasets
true_news['label']=0
fake_news['label']=1
df=pd.concat([true_news,fake_news], axis=0)
df=df.sample(frac=1,random_state=42).reset_index(drop=True)
print(df.shape)

(44898, 5)


In [5]:
from sklearn.model_selection import train_test_split
X=df[['title','text','subject','date']]
y=df['label']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1, random_state=42, stratify=y)
X1_train=X_train['text']
X1_test=X_test['text']

In [6]:
# encoding the dataset using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(lowercase=True, stop_words='english')
X_train_tfidf= tfidf.fit_transform(X1_train)
X_test_tfidf= tfidf.transform(X1_test)

In [7]:
# inspecting the new data
print(X_train_tfidf.shape)
X_train_tfidf.nnz / (X_train_tfidf.shape[0] * X_train_tfidf.shape[1])

(40408, 116807)


0.0013102371206605717

In [8]:
#training the machine
from sklearn.linear_model import LogisticRegression
log_reg= LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train_tfidf,y_train)
y_pred=log_reg.predict(X_test_tfidf)

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print("Accuracy :", accuracy_score(y_test, y_pred))
print("precision_score :", precision_score(y_test, y_pred))
print("recall_score :", recall_score(y_test, y_pred))
print("f1_score :" , f1_score(y_test,y_pred))

Accuracy : 0.9881959910913141
precision_score : 0.9889220281210055
recall_score : 0.9885008517887564
f1_score : 0.9887113951011715


In [10]:
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2116,   26],
       [  27, 2321]])

In [11]:
# inspecting the newses which were framed as true
fake_newses_framed_true=[]
for i in range(len(X_test)):
    if y_pred[i]==0 and y_test.iloc[i]==1:
        fake_newses_framed_true.append(X1_test.iloc[i])
for i in fake_newses_framed_true[1:5]:
    print(i,"\n")
print(len(fake_newses_framed_true))



Anyone who takes part in this type of sub-human criminal activity should never see the light of day again. The lawmakers who refuse to lock down our borders and stiffen the penalties for human traffickers who bring illegal aliens into the U.S. should also be held accountable by their constituents Eight people were found dead in a tractor-trailer outside a Walmart store in the stifling summer heat in what police called a horrific human trafficking case, and the driver was arrested.Several other people, possibly dozens, were found in the truck, which didn t have a working air conditioning system despite blistering temperatures that topped 100 degrees, and they were taken to hospitals, authorities said. The driver had been held, authorities said, but they didn t release the driver s identity.A person from the truck approached a Walmart employee in a parking lot and asked for water late Saturday night or early Sunday morning, said police in San Antonio, where temperatures on Saturday reach

In [12]:
# inspecting the fake newses which were termed fake
fake_newses_framed_fake=[]
for i in range(len(X_test)):
    if y_pred[i]==1 and y_test.iloc[i]==1:
        fake_newses_framed_fake.append(X1_test.iloc[i])
for i in fake_newses_framed_fake[40:60]:
    print(i,"\n")

We hear so much talk from the Left about working to help foreigners  assimilate. Yet here we have a prominent Imam calling for the segregation of Muslims from their host nation. How is this okay? Shaykh Said Rageah (     ) was born in Somalia and in the late 80s and moved to North America. Rageah has a Bachelor s in Islamic studies and a Masters in Shari ah and he has had several posts over the years, including: founder of Masjid Huda in Montreal and Masjid Aya in Maryland, advisor for Muslim Youth magazine, and member in the Aqsa Association.He is also the founder of both Muslim Magazine and Al Aqsa Association, and served as the Chaplain at both the University of Calgary and the Southern Alberta Institute of Technology (SAIT). He served as an Imam at the Abu Hurairah Mosque in Toronto, the Chairman for the Journey of Faith Conference and as an instructor for the AlMaghrib Institute.In a sermon delivered at Abu Hurairah Centre in Toronto (the video was uploaded to YouTube on February 

In [13]:
# inspecting true newses termed true
true_newses_framed_true=[]
for i in range(len(X_test)):
    if y_pred[i]==0 and y_test.iloc[i]==0:
        true_newses_framed_true.append(X1_test.iloc[i])
for i in true_newses_framed_true[50:60]:
    print(i,"\n")

COPENHAGEN (Reuters) - (This October 3 story has been refiled to Corrects detention period to four weeks, not four months, in seventh paragraph.) A Danish inventor charged with murdering Swedish journalist Kim Wall in his home-made submarine had video footage on his computer showing women being violently killed, a court heard on Tuesday. A police prosecutor said officers found images  which we presume to be real  of women being strangled and decapitated on the hard drive on Peter Madsen s computer in a laboratory he ran. That, together with new post-mortem evidence showing Wall was stabbed in her ribcage and genitals  around or shortly after her death,  was adding to the case against Madsen, the prosecutor, Jakob Buch-Jepsen, told the Copenhagen court. DNA tests from Madsen s nails, face and neck showed a clear match with Wall s, Buch-Jepsen said, though the exact cause of death remained unknown.  Our suspicion hasn t changed, it has been strengthened since (the last hearing on) Septem

In [14]:
#inspecting the true newses termed fake
true_newses_framed_fake=[]
for i in range(len(X_test)):
    if y_pred[i]==1 and y_test.iloc[i]==0:
        true_newses_framed_fake.append(X1_test.iloc[i])
for i in true_newses_framed_fake[0:20]:
    print(i,"\n")

SACRAMENTO, Calif. (Reuters) - California Governor Jerry Brown on Wednesday signed a bill to end the statute of limitations for rape, a measure inspired by accusations against comedian Bill Cosby, some of which surfaced decades after alleged crimes occurred. Cosby, who built a long career on family friendly comedy, including his long-running NBC sitcom “The Cosby Show,” has steadfastly denied ever assaulting anyone and has insisted that all his sexual encounters were consensual. He is charged in Pennsylvania with drugging and sexually assaulting a former Temple University employee, Andrea Constand, at his home in 2004. In California, he faces a civil suit by a woman now in her 50s who alleges that Cosby plied her with alcohol and molested her in 1974 at the Playboy Mansion when she was aged 15. Existing California law generally limits prosecution of a felony sexual offense to 10 years after the offense is committed. Only two in 100 rapists will be convicted of a felony and spend any ti

In [ ]:
# encoding without case conversion
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(lowercase=False,stop_words='english')
X_train_tfidf1= tfidf.fit_transform(X1_train)
X_test_tfidf1= tfidf.transform(X1_test)
print(X_train_tfidf1.shape)
print(X_train_tfidf1.nnz / (X_train_tfidf1.shape[0] * X_train_tfidf1.shape[1]))
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print("Accuracy :", accuracy_score(y_test, y_pred1))
print("precision_score :", precision_score(y_test, y_pred1))
print("recall_score :", recall_score(y_test, y_pred1))
print("f1_score :" , f1_score(y_test,y_pred1))
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred1)

(40408, 140636)
0.001171454066781014
Accuracy : 0.9910913140311804
precision_score : 0.9919011082693947
recall_score : 0.9910562180579217
f1_score : 0.9914784831700043


array([[2123,   19],
       [  21, 2327]])

In [20]:
y_proba= log_reg.predict_proba(X_test_tfidf1)[:,1]
import numpy as np
for t in [0.5, 0.3, 0.2]:
    y_predt= (y_proba>=t)
    print("Accuracy :", accuracy_score(y_test, y_predt))
    print("precision_score :", precision_score(y_test, y_predt))
    print("recall_score :", recall_score(y_test, y_predt))
    print("f1_score :" , f1_score(y_test,y_predt))
    print(confusion_matrix(y_test,y_predt))
    print("\n")


Accuracy : 0.9910913140311804
precision_score : 0.9919011082693947
recall_score : 0.9910562180579217
f1_score : 0.9914784831700043
[[2123   19]
 [  21 2327]]


Accuracy : 0.9850779510022272
precision_score : 0.9738263398421271
recall_score : 0.9982964224872232
f1_score : 0.9859095688748686
[[2079   63]
 [   4 2344]]


Accuracy : 0.9632516703786191
precision_score : 0.9350338780390594
recall_score : 0.9991482112436116
f1_score : 0.9660284126003706
[[1979  163]
 [   2 2346]]




In [22]:
# inspecting the newses which were framed as true
fake_newses_framed_true=[]
for i in range(len(X1_test)):
    if y_proba[i]<0.3 and y_test.iloc[i]==1:
        fake_newses_framed_true.append(X1_test.iloc[i])
for i in fake_newses_framed_true:
    print(i,"\n")
print(len(fake_newses_framed_true))

But wait wasn t the Muslim Brotherhood s Arab Spring (Sharia Law for all Egyptians) supposed to be a good thing? An Egyptian court sentenced Mohamed Badie, leader of the outlawed Muslim Brotherhood, and 13 other senior members of the group to death for inciting chaos and violence, and gave a life term to a U.S.-Egyptian citizen for ties to the Brotherhood.The men were among thousands of people detained after freely elected Islamist president Mohamed Mursi was toppled in 2013 by the military under Abdel Fattah al-Sisi, who is now president.Sisi describes the Brotherhood as a major security threat. The group says it is committed to peaceful activism and had nothing to do with Islamist militant violence in Egypt since Mursi s fall following mass protests against his rule.Egypt s mass trials of Brotherhood members and people accused of links to the group, as well as its tough crackdown on Islamist and liberal opposition alike, have drawn international criticism of its judicial system and h

In [35]:
# removing the token "reuters"
leakage_tokens = ["reuters"]
def remove_leakage(text):
    if not isinstance(text, str):
        return text
    for token in leakage_tokens:
        text = text.replace(token, "")
        text = text.replace(token.capitalize(), "")
        text = text.replace(token.upper(), "")
    return text
X2_train=X1_train.apply(remove_leakage)
X2_test= X1_test.apply(remove_leakage)
tfidf_clean = TfidfVectorizer(
    lowercase=False,
    stop_words="english"
)
X_train_tfidf2 = tfidf_clean.fit_transform(X2_train)
X_test_tfidf2 = tfidf_clean.transform(X2_test)
log_reg = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_reg.fit(X_train_tfidf2, y_train)
y_proba2 = log_reg.predict_proba(X_test_tfidf2)[:, 1]
y_pred2 = (y_proba2 >= 0.3)
print("Precision:", precision_score(y_test, y_pred2))
print("Recall:", recall_score(y_test, y_pred2))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred2))

Precision: 0.9641532756489494
Recall: 0.9965928449744463
Confusion matrix:
[[2055   87]
 [   8 2340]]


In [36]:
# inspecting the newses which were framed as true
fake_newses_framed_true=[]
for i in range(len(X1_test)):
    if y_proba2[i]<0.3 and y_test.iloc[i]==1:
        fake_newses_framed_true.append(X1_test.iloc[i])
for i in fake_newses_framed_true:
    print(i,"\n")
print(len(fake_newses_framed_true))

We all know by now that the biggest threat to the integrity of our vote is our very own President, the Democrat Party and their operatives. LOL! Russians are the least of our concerns The U.S. government is gearing up for an unprecedented effort to protect Tuesday s presidential election from cyber attack, U.S. officials told NBC News. There are a lot of eyes on this presidential election   more than there normally would be,  a senior Obama administration official said.Cyber centers at the Department of Homeland Security, the Justice Department and the FBI   as well as the Pentagon, the CIA and other intelligence agencies   will be on alert, with extra staff hunting for any possible threat, officials say.The concern is so high, intelligence officials told NBC, that for the first time, hundreds of military and intelligence cyber experts who work out of top secret facilities, including underground bunkers, will be monitoring intelligence about a U.S. presidential election. They will reac

In [64]:
def combine_title_body(title, body):
    return f"[TITLE] {title} [BODY] {body}"
X_train_tb = []
for i in range(len(X_train)):
    X_train_tb.append(combine_title_body(X_train.iloc[i]["title"],X2_train.iloc[i]))
X_test_tb=[]
for i in range(len(X_test)):
    X_test_tb.append(combine_title_body(X_test.iloc[i]["title"],X2_test.iloc[i]))
print(X_train_tb[1])

[TITLE] Trump trails Clinton by 8 points after tape scandal, debate: Reuters/Ipsos poll [BODY] NEW YORK () - Donald Trump has fallen further behind Hillary Clinton and now trails her by 8 points among likely voters, according to a new /Ipsos opinion poll, with 1 in 5 Republicans saying his vulgar comments about groping women disqualify him from the presidency.  The national tracking poll was launched after Sunday night’s second presidential debate, where Trump was pressed to explain his comments in a 2005 videotape about grabbing women’s genitalia. He described the remarks, which first surfaced on Friday, as “locker room” banter and apologized to Americans.  The poll released on Tuesday showed Clinton, the Democratic nominee, had increased her lead over Trump, the Republican nominee, to 8 percentage points on Monday from 5 points last week.  When asked to pick between the two major-party candidates, 45 percent of likely voters said they supported Clinton while 37 percent supported Trum

In [65]:
tfidf_tb = TfidfVectorizer(
    lowercase=False,
    stop_words="english"
)

X_train_tfidf_tb = tfidf_tb.fit_transform(X_train_tb)
X_test_tfidf_tb = tfidf_tb.transform(X_test_tb)

In [66]:
log_reg_tb = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_reg_tb.fit(X_train_tfidf_tb, y_train)

y_proba_tb = log_reg_tb.predict_proba(X_test_tfidf_tb)[:, 1]
y_pred_tb = (y_proba_tb >= 0.3).astype(int)
from sklearn.metrics import confusion_matrix, precision_score, recall_score

print("Precision:", precision_score(y_test, y_pred_tb))
print("Recall:", recall_score(y_test, y_pred_tb))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred_tb))

Precision: 0.9734439834024896
Recall: 0.9991482112436116
Confusion matrix:
[[2078   64]
 [   2 2346]]


In [68]:
# inspecting the newses which were framed as true
fake_newses_framed_true=[]
for i in range(len(X1_test)):
    if y_proba_tb[i]<0.3 and y_test.iloc[i]==1:
        fake_newses_framed_true.append(X_train_tb[i])
for i in fake_newses_framed_true:
    print(i,"\n")
print(len(fake_newses_framed_true))

[TITLE] Trump in crisis after lewd remarks about women come to light [BODY] NEW YORK/WASHINGTON () - Republican presidential candidate Donald Trump plunged into a deep crisis on Friday after a bombshell 2005 recording came to light in which he boasted in vulgar terms about trying to have sex with an unidentified married woman and groping women, saying “when you’re a star, they let you do it.” A stream of Republican leaders denounced the remarks, first published by the Washington Post, which threaten Trump’s already shaky standing with women voters just a month ahead of the Nov. 8 presidential election. House of Representatives Speaker Paul Ryan, the top Republican elected official, said he was “sickened” by the comments and said Trump would no longer attend a campaign event in Wisconsin with him on Saturday. “I hope Mr. Trump treats this situation with the seriousness it deserves and works to demonstrate to the country that he has greater respect for women than this clip suggests,” Rya