In [5]:
import numpy as np
A = np.array([ [12, 5, 8, 20], [ 7, 15, 3, 11], [25, 9, 18, 6], [10, 14, 2, 16] ])
m=np.mean(A,axis=1,keepdims=True)
print(m)


[[11.25]
 [ 9.  ]
 [14.5 ]
 [10.5 ]]


In [6]:
m=(A>m).astype(int)
print(m)    

[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [7]:
s=np.sum(m,axis=1)
n=np.max(s)
print(n)
print(np.where(s==n)[0])

2
[0 1 2 3]


In [8]:
X=np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15,115, 9] ])
m = np.mean(X, axis=0)
st = np.std(X, axis=0, keepdims=True)
median = np.median(X, axis=0)
outliers = np.abs(X - m) > 2 * st
print(outliers)
X_clean = X.copy()
X_clean[outliers] = np.broadcast_to(median, X.shape)[outliers]
print(X_clean)

[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False False]]
[[ 10 100   5]
 [ 12 110   6]
 [ 11 105   7]
 [ 13 109   6]
 [ 14 108   8]
 [ 15 115   9]]


In [9]:
import pandas as pd
df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],
'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],
'Gender': ['F','M','F','M','M','F','F','M'],
'Marks': [85,72,91,65,78,88,95,70],
'Attendance': [92,81,96,72,85,90,98,75] })
md=df.groupby('Department')['Marks'].mean()
print(md)
mdg=df.groupby(['Department','Gender'])['Marks'].mean()
hd=df.groupby('Department')['Marks'].max()
dept_avg = df.groupby('Department')['Marks'].transform('mean')
print(df[df['Marks']>dept_avg])
ad=max(md)

Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64
  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
2       C        ECE      F     91          96
5       F        ECE      F     88          90
6       G        CSE      F     95          98


In [10]:
df = pd.DataFrame({
    'ID': [101,102,103,101,104,102,105],
    'Name': ['A','B','C','A','D','B','E'],
    'Age': [20,21,22,20,23,21,24],
    'Score': [80,75,90,85,88,75,92]
})
duplicated_ids = df[df['ID'].duplicated(keep=False)]['ID'].unique()
print(duplicated_ids)

[101 102]


In [11]:
duplicates = df[df['ID'].duplicated(keep=False)]

identical = duplicates.groupby('ID').apply(
    lambda x: x.drop(columns='ID').nunique().max() == 1
)
print(identical)

ID
101    False
102     True
dtype: bool


/var/folders/yf/blbfthrd185738f9dyfzy7qw0000gn/T/ipykernel_1372/3448468820.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  identical = duplicates.groupby('ID').apply(


In [12]:
df_sorted = df.sort_values('Score', ascending=False)
clean_df = df_sorted.drop_duplicates('ID', keep='first')
clean_df = (
    df.sort_values('Score', ascending=False)
      .drop_duplicates('ID', keep='first')
      .sort_values('ID')
      .reset_index(drop=True)
)

print(clean_df)

    ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92


In [13]:
removed = len(df) - len(clean_df)
print("Records removed:", removed)

Records removed: 2


In [14]:
df = pd.DataFrame({
    'Date': [
        '2026-01-01', '2026-01-02', '2026-01-04',
        '2026-01-05', '2026-01-08', '2026-01-09'
    ],
    'Sales': [100, 120, 150, 130, 180, 200]
})
df['Date'] = pd.to_datetime(df['Date'])
full_dates = pd.date_range(
    df['Date'].min(),
    df['Date'].max(),
    freq='D'
)
missing_dates = full_dates.difference(df['Date'])
print("Missing dates:", missing_dates)
df = df.set_index('Date').reindex(full_dates)
df['Rolling_Avg'] = df['Sales'].rolling(3).mean()
print(df)
print("Maximum rolling average date:", df['Rolling_Avg'].idxmax())

Missing dates: DatetimeIndex(['2026-01-03', '2026-01-06', '2026-01-07'], dtype='datetime64[ns]', freq=None)
            Sales  Rolling_Avg
2026-01-01  100.0          NaN
2026-01-02  120.0          NaN
2026-01-03    NaN          NaN
2026-01-04  150.0          NaN
2026-01-05  130.0          NaN
2026-01-06    NaN          NaN
2026-01-07    NaN          NaN
2026-01-08  180.0          NaN
2026-01-09  200.0          NaN
Maximum rolling average date: NaT


/var/folders/yf/blbfthrd185738f9dyfzy7qw0000gn/T/ipykernel_1372/237517469.py:19: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  print("Maximum rolling average date:", df['Rolling_Avg'].idxmax())


In [16]:
import numpy as np
P = np.array([
    [1, 2],
    [4, 6],
    [7, 3],
    [2, 8],
    [9, 5]
])
diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]
# Euclidean distances
D = np.sqrt(np.sum(diff**2, axis=2))
print(D)

[[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]


In [17]:
i, j = np.unravel_index(np.argmax(D), D.shape)
print("Maximum distance:", D[i, j])
print("Point pair:", i, j)

Maximum distance: 8.54400374531753
Point pair: 0 4
